# Generated by Django 5.0.3 on 2024-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project_1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresponse",
            name="selected_option",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.AddField(
            model_name="question",
            name="question_text",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="UserResponse",
        ),
    ]
